name: Python Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.10 (to match your project)
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest

    # Step 4: Run Flake8 for linting
    - name: Run Flake8 for linting
      run: |
        flake8 . --max-line-length=150
      continue-on-error: false

    # Step 5: Check code formatting using Black
    - name: Check code formatting with Black
      run: |
        black --check .
      continue-on-error: false

    # Step 6: Run tests with pytest
    - name: Run tests with pytest
      run: |
        pytest --ignore=mysql/db
      continue-on-error: false